# Generated by Django 4.0.1 on 2022-01-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(max_length=150, verbose_name='Тип судна')),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=150, verbose_name='Пункт назначения')),
                ('load', models.CharField(max_length=150, verbose_name='груз')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw.first')),
            ],
        ),
    ]
